spring.application.name=CompilerProject
server.port=8082
BASE_DIR=/mnt/tmpfs/
spring.mongodb.uri=mongodb+srv://satyam-atishay:LiqpJeE4voJJQe40@cluster0.b5t6vyd.mongodb.net/compiler?appName=Cluster0
spring.data.mongodb.auto-index-creation=true
JWT_SECRET_KEY=MsgSPjcvFcSEtzL87RtZx3TqK1KF+k3DxO+oQBbPkbUH5bzHwClR4+lNzDYjEothjbYH0ilA1YHYsYEh3tn/qqUvJ+d6h7ACS/bokS5Ehn0Dg9DZM8Ank/K9iyoy0Y1+hrNMLvLoKBQQEeBWuyk/Nk5YkF+1WQNWCDwGBpyM3A=
